workflows:
  android-app:
    name: Build Kotlin APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PROJECT_PATH: "app"
    scripts:
      - name: Clean and get dependencies
        script: |
          cd $PROJECT_PATH
          ./gradlew clean
          ./gradlew dependencies

      - name: Build APK
        script: |
          cd $PROJECT_PATH
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
